const colors = [
  { name: "AliceBlue", value: "aliceblue" },
  { name: "AntiqueWhite", value: "antiquewhite" },
  { name: "Aqua", value: "aqua" },
  { name: "Aquamarine", value: "aquamarine" },
  { name: "Azure", value: "azure" },
  { name: "Beige", value: "beige" },
  { name: "Bisque", value: "bisque" },
  { name: "Black", value: "black" },
  { name: "BlanchedAlmond", value: "blanchedalmond" },
  { name: "Blue", value: "blue" },
  { name: "BlueViolet", value: "blueviolet" },
  { name: "Brown", value: "brown" },
  { name: "BurlyWood", value: "burlywood" },
  { name: "CadetBlue", value: "cadetblue" },
  { name: "Chartreuse", value: "chartreuse" },
  { name: "Chocolate", value: "chocolate" },
  { name: "Coral", value: "coral" },
  { name: "CornflowerBlue", value: "cornflowerblue" },
  { name: "Cornsilk", value: "cornsilk" },
  { name: "Crimson", value: "crimson" },
  { name: "Cyan", value: "cyan" },
  { name: "DarkBlue", value: "darkblue" },
  { name: "DarkCyan", value: "darkcyan" },
  { name: "DarkGoldenRod", value: "darkgoldenrod" },
  { name: "DarkGray", value: "darkgray" },
  { name: "DarkGreen", value: "darkgreen" },
  { name: "DarkKhaki", value: "darkkhaki" },
  { name: "DarkMagenta", value: "darkmagenta" },
  { name: "DarkOliveGreen", value: "darkolivegreen" },
  { name: "DarkOrange", value: "darkorange" },
  { name: "DarkOrchid", value: "darkorchid" },
  { name: "DarkRed", value: "darkred" },
  { name: "DarkSalmon", value: "darksalmon" },
  { name: "DarkSeaGreen", value: "darkseagreen" },
  { name: "DarkSlateBlue", value: "darkslateblue" },
  { name: "DarkSlateGray", value: "darkslategray" },
  { name: "DarkTurquoise", value: "darkturquoise" },
  { name: "DarkViolet", value: "darkviolet" },
  { name: "DeepPink", value: "deeppink" },
  { name: "DeepSkyBlue", value: "deepskyblue" },
  { name: "DimGray", value: "dimgray" },
  { name: "DodgerBlue", value: "dodgerblue" },
  { name: "FireBrick", value: "firebrick" },
  { name: "FloralWhite", value: "floralwhite" },
  { name: "ForestGreen", value: "forestgreen" },
  { name: "Fuchsia", value: "fuchsia" },
  { name: "Gainsboro", value: "gainsboro" },
  { name: "GhostWhite", value: "ghostwhite" },
  { name: "Gold", value: "gold" },
  { name: "GoldenRod", value: "goldenrod" },
  { name: "Gray", value: "gray" },
  { name: "Green", value: "green" },
  { name: "GreenYellow", value: "greenyellow" },
  { name: "HoneyDew", value: "honeydew" },
  { name: "HotPink", value: "hotpink" },
  { name: "IndianRed", value: "indianred" },
  { name: "Indigo", value: "indigo" },
  { name: "Ivory", value: "ivory" },
  { name: "Khaki", value: "khaki" },
  { name: "Lavender", value: "lavender" },
  { name: "LavenderBlush", value: "lavenderblush" },
  { name: "LawnGreen", value: "lawngreen" },
  { name: "LemonChiffon", value: "lemonchiffon" },
  { name: "LightBlue", value: "lightblue" },
  { name: "LightCoral", value: "lightcoral" },
  { name: "LightCyan", value: "lightcyan" },
  { name: "LightGoldenRodYellow", value: "lightgoldenrodyellow" },
  { name: "LightGray", value: "lightgray" },
  { name: "LightGreen", value: "lightgreen" },
  { name: "LightPink", value: "lightpink" },
  { name: "LightSalmon", value: "lightsalmon" },
  { name: "LightSeaGreen", value: "lightseagreen" },
  { name: "LightSkyBlue", value: "lightskyblue" },
  { name: "LightSlateGray", value: "lightslategray" },
  { name: "LightSteelBlue", value: "lightsteelblue" },
  { name: "LightYellow", value: "lightyellow" },
  { name: "Lime", value: "lime" },
  { name: "LimeGreen", value: "limegreen" },
  { name: "Linen", value: "linen" },
  { name: "Magenta", value: "magenta" },
  { name: "Maroon", value: "maroon" },
  { name: "MediumAquaMarine", value: "mediumaquamarine" },
  { name: "MediumBlue", value: "mediumblue" },
  { name: "MediumOrchid", value: "mediumorchid" },
  { name: "MediumPurple", value: "mediumpurple" },
  { name: "MediumSeaGreen", value: "mediumseagreen" },
  { name: "MediumSlateBlue", value: "mediumslateblue" },
  { name: "MediumSpringGreen", value: "mediumspringgreen" },
  { name: "MediumTurquoise", value: "mediumturquoise" },
  { name: "MediumVioletRed", value: "mediumvioletred" },
  { name: "MidnightBlue", value: "midnightblue" },
  { name: "MintCream", value: "mintcream" },
  { name: "MistyRose", value: "mistyrose" },
  { name: "Moccasin", value: "moccasin" },
  { name: "NavajoWhite", value: "navajowhite" },
  { name: "Navy", value: "navy" },
  { name: "OldLace", value: "oldlace" },
  { name: "Olive", value: "olive" },
  { name: "OliveDrab", value: "olivedrab" },
  { name: "Orange", value: "orange" },
  { name: "OrangeRed", value: "orangered" },
  { name: "Orchid", value: "orchid" },
  { name: "PaleGoldenRod", value: "palegoldenrod" },
  { name: "PaleGreen", value: "palegreen" },
  { name: "PaleTurquoise", value: "paleturquoise" },
  { name: "PaleVioletRed", value: "palevioletred" },
  { name: "PapayaWhip", value: "papayawhip" },
  { name: "PeachPuff", value: "peachpuff" },
  { name: "Peru", value: "peru" },
  { name: "Pink", value: "pink" },
  { name: "Plum", value: "plum" },
  { name: "PowderBlue", value: "powderblue" },
  { name: "Purple", value: "purple" },
  { name: "RebeccaPurple", value: "rebeccapurple" },
  { name: "Red", value: "red" },
  { name: "RosyBrown", value: "rosybrown" },
  { name: "RoyalBlue", value: "royalblue" },
  { name: "SaddleBrown", value: "saddlebrown" },
  { name: "Salmon", value: "salmon" },
  { name: "SandyBrown", value: "sandybrown" },
  { name: "SeaGreen", value: "seagreen" },
  { name: "SeaShell", value: "seashell" },
  { name: "Sienna", value: "sienna" },
  { name: "Silver", value: "silver" },
  { name: "SkyBlue", value: "skyblue" },
  { name: "SlateBlue", value: "slateblue" },
  { name: "SlateGray", value: "slategray" },
  { name: "Snow", value: "snow" },
  { name: "SpringGreen", value: "springgreen" },
  { name: "SteelBlue", value: "steelblue" },
  { name: "Tan", value: "tan" },
  { name: "Teal", value: "teal" },
  { name: "Thistle", value: "thistle" },
  { name: "Tomato", value: "tomato" },
  { name: "Turquoise", value: "turquoise" },
  { name: "Violet", value: "violet" },
  { name: "Wheat", value: "wheat" },
  { name: "White", value: "white" },
  { name: "WhiteSmoke", value: "whitesmoke" },
  { name: "Yellow", value: "yellow" },
  { name: "YellowGreen", value: "yellowgreen" }
];
let Boss=document.querySelector(".Boss");
let changeColor=document.querySelector(".changeColor");
let nameOfColor=document.querySelector(".nameOfColor");
changeColor.onclick=()=>{
    let random=colors[Math.floor(Math.random()*colors.length)].value;
    Boss.style.backgroundColor=random;
    nameOfColor.textContent=random;
}
 let reset=document.querySelector(".reset");
 reset.onclick=()=>{
    Boss.style.backgroundColor="white";
    nameOfColor.textContent="white";
 }

